.github/workflows/release.yaml

Fix: Update chart_repo_url with custom DNS
#
#
#

fix: Update chart_repo_url with custom DNS

---

.github/workflows/lint-test.yaml

Test out lint with github actions workflows.
#
#
#

fix: Add lint test

---

README.md
charts/deps/README.md
charts/openmetadata/README.md

Update documentation to install openmetadata helm charts from artifacthub.io
#
#
#
@shahsank3t @sureshms @harshach @ayush-shah

fix: Update documentation

---

.github/workflows/lint-test.yaml
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

- App Version and Helm Chart version updated
> This PR is dependent on 0.6.0 Release for open-metadata/OpenMetadata. Please make sure to merge the changes here post the release.
#
#
#

feat: Prepare for 0.6.0 Release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Version bump for 0.7.0 Openmetadata Release.
#
#
#

feat: bump up versions for 0.7.0 release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Helm Charts 0.8.0 Release
#
#
#

Feat: 0.8.0 Release

---

README.md
charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/templates/service.yaml
charts/openmetadata/values.yaml

This PR -
- Updates bitnami/mysql to `8.8.23`
- Adds support for openmetadata config environment variables (fixes #10)
- Fixes service ports and updates README's
- Prepares for chart version 0.0.5 release
#
#
#

fix: helm chart and miscellaneous updates

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_script.tpl
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/db-migrations-hook-cm.yaml

This PR fixes the db migrations when upgrading to next release. This is achieved by Helm Chart Hooks.
Fixes [#2502](https://github.com/open-metadata/OpenMetadata/issues/2502) and [#1475](https://github.com/open-metadata/OpenMetadata/issues/1475)
Helm Hooks helps you listen to Helm Chart release lifecycle and provides a way to interact with the same. One such scenario is to upgrade database migrations before jumping to new release.
We are using Helm _pre-upgrade_ hook. Just before upgrade, Helm spins up a Job and executes database validation and migration scripts.
- Current Users upgrading Helm Charts by deleting existing openmetadata release (old version. example - 0.0.5) and and installing new version release (new version. example - 0.0.6) [This is an edge case and **not recommended for …

feat: helm hooks to provide assistance on db migrations

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml

Fixes #19 and release for docker image 0.8.3
#
#
#

feat: release 0.8.3

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_deployment_helpers.tpl
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

Support for sidecar containers. Fixes #17 
#
#
#

feat: Support for OpenMetadata sidecars

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml

Updated Chart AppVersions to new release 0.8.4
#
#
#

feat: OpenMetadata Release for 0.8.4

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/_script.tpl
charts/openmetadata/templates/check-db-migrations-job-hook.yaml

This PR fixes upgrade hooks failure when testing out preview docker releases.
#
#
#

fix: Upgrade Hooks

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

This PR contains a bunch of added globals values to ease OpenMetadata Configuration right from Helm Values.
- Ability to provide Authorizer and Authentication Attributes for OpenMetadata Server
- Ability to provide Truststore and Secret Key for ElasticSearch
On Upgrade, we have unified `secretKey` names for mysql and airflow password secrets. This will break existing default upgrades unless you have through values.yaml.
Run the below command to create secrets for airflow and mysql with default secretKey name -
```
kubectl create secret generic mysql-secrets --from-literal=openmetadata-mysql-password=openmetadata_password
kubectl create secret generic airflow-secrets --from-literal=openmetadata-airflow-password=admin
```
#
#
#

feat: Release for 0.9.0

---

README.md

Updating Secrets Command.
Fixes #26 .
#
#
#

docs: updating secrets command

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/values.yaml

fix: Typo for elasticsearch secret

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Helm Chart Release for OpenMetadata version 0.9.1.
#
#
#

feat: Release 0.9.1

---

.github/pull_request_template.md
README.md

I found that some links are old so updated them.
- Link to "Build Code and Run Tests" on the README
- Link to the document for developers on the pull request template
#
#
</p>
#
#
@akash-jain-10

docs: fix doc links

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

This PR brings in major changes / additions of ability to configure OpenMetadata Server.
Additions -
Deprecations -
Changes -
#
#
#

feat: OpenMetadata Helm Chart Release for 0.10.0

---

.github/workflows/lint-test.yaml
charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/deps/README.md
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/values.yaml

Airflow Helm Charts now integrated with OpenMetadata Dependencies. This will enable Ingestion From UI support right from OpenMetadata helm charts.
#
#

feat: Add airflow helm charts to OpenMetadata dependencies

---

.github/workflows/release.yaml
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml

fix: Release CI fix

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/values.yaml

Enable Airflow Configurations by default
#
#
#

fix: Enable Airflow Configurations by default

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml

ES defaults updated and Airflow dag_generated_configs path updated.
#
#

fix: ES defaults updated & Airflow dag_generated_configs path updated

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

0.10.1 Release.
Added ability to provide JWT Configurations through values.yaml
#
#

Feat: 0.10.1 Release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/deployment.yaml

fixes #42 and #43

---

README.md
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/values.yaml

OpenMetadata 0.10.2 release for Helm Charts.
Also fixes #45 .
#
#

feat: OpenMetadata 0.10.2 release for Helm Charts

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

See https://github.com/open-metadata/OpenMetadata/releases/tag/0.10.3-release
#
#
#

feat: OpenMetadata 0.10.3 release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

OpenMetadata Release 0.10.4
#
#
#

openmetadata release 0.10.4

---

README.md

I worked on the README because make more easy for newcomer to execute command
#
#
#
@shahsank3t

feat: improve kubectl to port-forward in local

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare for 0.11.2 release
#
#
#

feat: Prepare for 0.11.2 release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/NOTES.txt
charts/openmetadata/templates/ingress.yaml
charts/openmetadata/values.yaml

I worked on introducing ingress in the chart because i want to make simple for users deploy the application
#
#
#
@akash-jain-10)

feat: introduce ingress in chart

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare for 0.11.3 release
#
#
#

feat: Prepare for openmetadata 0.11.3 release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare for 0.11.4 release
#
#
#

feat: Prepare for 0.11.4 release

---

.github/workflows/datree.yaml
.github/workflows/test/openmetadata-values.yaml

I worked on the helm template validation because we want to be sure that there is not templated output that is not valid.
#
#
#
@akash-jain-10
- Can I ask to introduce a secret in github that allow to connect with the https://datree.io/ ? The service is free for community usage and will allow you to get reports on the generated template from helm for all the kubernetes version that should be supported.

Add support for chart testing

---

.github/workflows/datree.yaml
.github/workflows/test/openmetadata-values.yaml
charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/ingress.yaml

I worked on the Datree validation in CI because it was broken for kubernetes 1.13 and 1.14
#
#
#
@akash-jain-10

Add Datree support for kubernetes 1.13 and 1.14

---

.github/workflows/datree.yaml

I worked on the fixing the datree validation because the main branch build fails.
The issues we have is similar to the one describe on https://github.com/datreeio/action-datree/issues/9
I tested on my repo that it works as expected (see https://github.com/mavimo/openmetadata-helm-charts/runs/7712118177?check_suite_focus=true )
#
#
#
@akash-jain-10

fix datree escaping (see https://github.com/datreeio/action-datree/isssues/9)

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

Add Support for FernetKey Configuration #63
#
#
#

fix: Add Support for FernetKey Configuration #63

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare for 0.11.5 release
#
#
#

feat: Prepare for 0.11.5 release

---

charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

Prepare OpenMetadata Helm Charts with 0.12 Release
- Added values for OpenMetadata Secrets Manager
- Updated Environment Variable names for DB_*
- Updated Airflow Helm Dependency to 2.3.3 (Airflow Helm Version 8.6.1)
#
#
</p>
#
#

feat: Prepare OpenMetadata Helm Charts with 0.12 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml

Fix as per DIscussions here - https://openmetadata.slack.com/archives/C02B6955S4S/p1662715548737879
#
#
#

fix: airflow-helm 2.3.3

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml

see [#7641](https://github.com/open-metadata/OpenMetadata/issues/7641)
#
#
</p>
#
#

updating Helm Charts with the database airflow_db with proper character set and collate and chart version to 0.0.38

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

Also fixes #77  with default storage volumes to be 50Gi.
Below are the updates taken care -
#
#
#

feat: Release 0.12.1

---

.github/workflows/datree.yaml

Added support for kubernetes 1.25 into testing environments to prevent potential issues
#
#
#
@akash-jain-10

Enable object validation for kubetenes 1.25

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

I worked on this for new release

New Release of Helm Chart version 0.12.2

---

charts/openmetadata/Chart.yaml
charts/openmetadata/templates/deployment.yaml

Fixes [ISSUE-87](https://github.com/open-metadata/openmetadata-helm-charts/issues/87)
#
@harshach

deployment template fix when elasticsearch trustStore is enabled.

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/_validate-values.tpl
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/templates/validate-values.tpl

adding checks to validating auth-provider

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/deployment.yaml

fixes #90 
tested out with below scenarios -
```yaml
global:
...
authentication:
publicKeys:
- "http://openmetadata:8585/api/v1/config/jwks?test=123"
- http://openmetadata:8585/api/v1/config/jwks?test=456
- 'http://openmetadata:8585/api/v1/config/jwks?test=789'
...
```
```yaml
global:
...
authentication:
publicKeys:
- "http://openmetadata:8585/api/v1/config/jwks?test=123"
...
```
```yaml
global:
...
authentication:
publicKeys:
- "http://openmetadata:8585/api/v1/config/jwks?test=123"
- http://openmetadata:8585/api/v1/config/jwks
...
```
> This is a backward compatible bug fix.
#
#
#

fix: Array of string env values

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Release 0.12.3 for Helm Charts
#
#
#

feat: Release 0.12.3 for Helm Charts

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/check-db-migrations-job-hook.yaml
charts/openmetadata/templates/db-migrations-hook-cm.yaml
charts/openmetadata/values.schema.json

- Application Version Bump to 0.13.0
- Helm Chart Versions Bump to 0.0.47
- Mark botPrincipals as Deprecated in jsonSchema
- tweak helm hooks for better use with argocd (probably)
#
#
#

feat: Prepare OpenMetadata 0.13.0 Helm Chart Release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.yaml

I worked on the #99 and updated configurations
#
- [] Bug fix
- [] New feature
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation

updating changes for issue_99

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

I worked on updating the values.schema.json and readme file with secret key information.
#
#

Updating README.md and values.schema.json file

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/secrets.yaml
charts/openmetadata/values.yaml

I worked on the issue #111 and adding annotations in the secret to resolve the bug for the helm upgrade. 
#
#
#

helm bug issue 111

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/check-db-migrations-job-hook.yaml

I worked on the ISSUE-115 because i currently deploying OpenMetadata in GKE in a specific NodePool (in our organization, we use a mutualized GKE Cluster)
#
#
</p>
#
#
@akash-jain-10

ISSUE-115: Add nodeSelector,affinity,tolerations specs

---

.github/workflows/release.yaml
.github/workflows/test/openmetadata-values.yaml
charts/openmetadata/templates/check-db-migrations-job-hook.yaml

Switch to workflow dispatch for releases. This will help the contributors update the code as per their contributions and we take care of version bumping and releases with multiple contributions packed.
#
#
</p>
#
#

fix: switch to workflow dispatch for releases

---

charts/openmetadata/templates/check-db-migrations-job-hook.yaml

I worked on the migration hook job because the imagepullsecret was not included there.
#
#
@akash-jain-10

expand pull secrets in migration hook

---

charts/openmetadata/values.schema.json

I worked on the updating json schema conditions for https://github.com/open-metadata/openmetadata-helm-charts/issues/84 
#
#
#

Adding Json Schema constraints in ref Issue-84

---

charts/deps/values.yaml

Fixed a typo in a comment in the dependencies helm chart
#
#
#
@akash-jain-10

Fix typo in comment in dependencies helm chart

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare helm charts for 1.0.1 Release
#
#
#

feat: Prepare helm charts for 1.0.1 Release

---

charts/openmetadata/README.md

Fixed a typo in the readme I came across.
#
#
#
@akash-jain-10

Fix typo in README

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare Helm Charts for 1.0.2 Application Version Release.
#
#
#

feat: Prepare Helm Charts for 1.0.2 Application Version Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

feat: Prepare for 1.0.3 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare Helm Charts for Application version 1.0.4 Release.
#
#
</p>
#
#

feat: Prepare Helm Charts Publish for 1.0.4 Application Version Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare Helm Chart 1.0.5 Release
#
#
</p>
#
#

feat: Prepare Helm Chart 1.0.5 Release

---

charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

This PR contains the following changes -
- [Add keepAliveTimeoutSecs to ElasticSearch](https://github.com/open-metadata/openmetadata-helm-charts/commit/49f9e3a795f9eb9bf138abc5efbb582c2b6168d9)
- [Add healthCheckInterval in pipelineServiceClientConfig](https://github.com/open-metadata/openmetadata-helm-charts/commit/0f434dd51eb4c189f6b936daf8090dc4dd2fb2b5)
- [Added Search Type for ElasticSearch config](https://github.com/open-metadata/openmetadata-helm-charts/commit/1de280338b1a768d0e26ee8b3f506ad25e5fdb91)
- [Update to ES version 7.16.1](https://github.com/open-metadata/openmetadata-helm-charts/commit/ee4bcef350f2ebf84e9aaafe4d124f9f091aa3b3)
#
#
#

feat: Prepare 1.1.0 Release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml

I worked on the ..... because ...
#
#
</p>
#
#

fixing app version for artifact hub

---

.gitignore
charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

[fix: add migration flags; feat: add web block](https://github.com/open-metadata/openmetadata-helm-charts/commit/e7f1a46d6eb05064833d67978b94c0276f74e452)
[fix(chore): version bump](https://github.com/open-metadata/openmetadata-helm-charts/commit/9ba13af3b195baa071a0a3b78c4ab271d23c3b85)
[remove deprecated examples!](https://github.com/open-metadata/openmetadata-helm-charts/commit/b2120a44e18d01bab0c2e49e2b6da4950ff4d93d)
[fix: upgradeMigrationConfigs.force: false](https://github.com/open-metadata/openmetadata-helm-charts/commit/619930ab4eb5952dd9ee88362ae28ab6d4692c50)
[feat: update airflow helm chart dependencies to 8.7.1](https://github.com/open-metadata/openmetadata-helm-charts/commit/0ecd788770bfbd322af304f44eaac1967c509c25)
[fix(docs): Update readme with …

feat: Prepare 1.1.1 Release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/templates/deployment.yaml

fix: Missing volume mounts in init-containers #173

---

charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

I worked on the ..... because ...
#
- [] Bug fix
- [] Improvement
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
#
#
#

Adding new env variables of openmetadata.config.web.*

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Version Bump for 1.1.2 Application Release.
#
#
#

fix(chore): Version bump for 1.1.2

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

feat: Prepare 1.1.3 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

feat: Prepare 1.1.4 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare 1.1.6 Release
#
#
</p>
#
#

feat: Prepare 1.1.6 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare Helm Charts for 1.1.7 Release.
#
#
#

feat(release): Update Release versions

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml

ES Disable Security and HTTPS which was enabled by default
#
#
#

fix: ES Disable Security and HTTPS which was enabled by default

---

charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/README.md
charts/openmetadata/values.yaml

feat: Migrate to OpenSearch 2.7 as Chart's default search dependency

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Version Bump to 1.2.2 Application Release
#
#
</p>
#
#

chore: Version Bump to 1.2.2 Application Release

---

charts/openmetadata/templates/poddisruptionbudget.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

I worked on the Pod Disruption Budget for Openmetadata server to ensure availability of the server pod.
#
#
@akash-jain-10

Introduction of poddisruptionbudget for openmetadata server

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/pull_request_template.md

Added a couple of issue report templates for:
- Bug report
- Feature request
Also updated the Pull request template for the repository.
Here are the preview images for these templates:
- **Bug Report:**
- **Feature Request:**
#
#
#
@akash-jain-10

Add Bug Report, Feature Request Templates, and update Pull Request Template

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/deployment.yaml
charts/openmetadata/templates/secrets.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

feat: Prepare 1.3.0 Release

---

charts/openmetadata/templates/deployment.yaml

fix: Indentation issue for `envFrom` helm values

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/values.yaml

Fixes #222 with making additionalParameters as optional in case of using managed aws and azure secrets manager.
#
#
#

feat: Prepare 1.3.3 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

chore: Bump Versions for `1.3.4` Release

---

charts/deps/Chart.yaml
charts/openmetadata/Chart.yaml

`Chart.yaml` manifest icon link
#
#
#

fix: `Chart.yaml` manifest icon link

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/secrets.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

Added Environment configurations for `useRolesFromProvider` and `payLoadSize`.
#
#
#

feat: Prepare Release `1.4.0`

---

charts/openmetadata/Chart.yaml
charts/openmetadata/templates/secrets.yaml

bump version & fix payloadSize template

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare Charts for `1.4.1` Release
#
#
#

feat: Prepare Charts for `1.4.1` Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

chore: Bump versions for `1.4.2` Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Helm Chart Release for `1.4.3`
#
#
#

chore: Bump versions to `1.4.3` Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/secrets.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

feat: Prepare `1.4.4` Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Bump versions for `1.4.5` Release
#
#
#

chore: Bump versions for `1.4.5` Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/secrets.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

feat: Prepare 1.4.6 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

feat: Prepare 1.4.7 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Prepare Release 1.5.1

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

chore: bump version to 1.5.3

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

chore: bump version to 1.5.4

---

charts/openmetadata/templates/secrets.yaml

Fixes #259 
#
#
#
@akash-jain-10 @tutte @dhruvinmaniar123

openmetadata: Fix typo which prevents deployment

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md
charts/openmetadata/templates/tests/test-connection.yaml

feat: Prepare 1.5.5 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Update values to `1.5.6` release

feat: Prepare 1.5.6 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Update values to `1.5.7` release

feat: Prepare 1.5.7 Release

---

charts/deps/Chart.yaml
charts/deps/values.yaml
charts/openmetadata/Chart.yaml
charts/openmetadata/README.md

Update values to `1.5.8` release

feat: Prepare 1.5.8 Release

---

charts/openmetadata/README.md

chore: Update Docs

---

.github/workflows/lint-test.yaml

Fixes #282
Updated `ct lint --target-branch=${{ env.default_branch }} ` to skip version checks over CI.
#
#
#

updated skip lint test 

---

charts/openmetadata/README.md
charts/openmetadata/templates/_helpers.tpl
charts/openmetadata/templates/cron-reindex.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

Fixes #287 
created cronjob for reindex
#
- [] Bug fix
#
#

Feat: created cronjob for reindex

---

charts/openmetadata/templates/_helpers.tpl

fix: Use GCP Secrets Manager additional Parameters
#
#
#

fix: Use GCP Secrets Manager additional Parameters

---

charts/openmetadata/Chart.yaml

fix: Bump server Docker image version to 1.6.1

---

charts/openmetadata/templates/_helpers.tpl

fixed the command for reindex cron
ISSSUE-302
Fixes #
#
#
#

ISSUE-302: fix command for k8s reindex cronjob

---

.github/workflows/lint-test.yaml

Fixed the error to solve the `lint-test.yaml` workflow issue.
Fixes #
#
#
#

feat: Updated the version of setup-python to solve the workflow issue

---

charts/openmetadata/README.md
charts/openmetadata/templates/secrets.yaml
charts/openmetadata/values.schema.json
charts/openmetadata/values.yaml

Add support for OIDC prompt type

---

.pre-commit-config.yaml
README.md

Added Chart-testing linting tool to lint HELM Charts.
Fixes #291
#
#
#

Added ct-lint

---

charts/deps/Chart.lock
charts/deps/Chart.yaml
charts/deps/values.yaml

Upgraded MySQL Helm chart version to `10.3.0` and Helm values to use `bitnamilegacy/mysql:8.0.37-debian-12-r2`, because Bitnami has moved their older chart versions to Bitnami Legacy while charging for newer versions.
To maintain compatibility and ensure continued access, we shifted to the legacy repository image and upgraded the chart version accordingly.
How it was tested / validated:
Deployed the Helm chart using the previous MySQL version for baseline validation.
Upgraded to:
Helm Chart version: 10.3.0
MySQL Image: bitnamilegacy/mysql:8.0.37-debian-12-r2
Ran `helm dependency update` followed by:
`helm upgrade --install openmetadata-dependencies open-metadata/openmetadata-dependencies --values values.yaml`
Verified pods functionality using:
`kubectl get pods` All the pods spins up …

mysql: Updated mysql to use bitnami legacy images
