open-metadata/openmetadata-helm-charts

charts/deps/Chart.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/templates/check-db-migrations-job-hook.yaml
* The sidecar container has added to the Deployment object, and it should also be added to the database migration script as well.
* We use sidecar container to host database auth proxy, which it helps us achieving more convenient TLS setup and access control.
* In all K8S objects where the OMD MySQL database is accessed, the sidecar container should be available.
=> Add side car to the database migration script

.github/workflows/datree.yaml
This fix the wrong kube version used in the chart validation
#
#
#
@akash-jain-10
=> Fix kube version used in helm chart templating

charts/deps/Chart.yaml
Missed sync-ing chart version as part of the previous [PR](https://github.com/open-metadata/openmetadata-helm-charts/pull/86) which fixed [ISSUE-87](https://github.com/open-metadata/openmetadata-helm-charts/issues/87)
@harshach
=> bumped chart version for deps as well

charts/deps/Chart.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/templates/check-db-migrations-job-hook.yaml
This applies the same fix for elasticsearch truststore config as done in [this previous PR](https://github.com/open-metadata/openmetadata-helm-charts/pull/86), but in the db migration hook. Chart version bump is required in both Chart.yamls.
#
#
#
@harshach
=> updated missed elasticsearch truststore config in db migration hook too

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/deps/Chart.lock, charts/deps/Chart.yaml, charts/openmetadata/Chart.yaml
As per the Bitnami Repository Index change as mentioned [here](https://github.com/bitnami/charts/issues/10833), we are reverting the helm chart dependency usage back to 8.8.23 for now.
#
#
#
=> fix: revert mysql deps to 8.8.23

charts/deps/Chart.yaml, charts/deps/values.yaml
If the Chart is installed outside of `default` namespace, it won't start properly with default values.  
This change allows to resolve the database that is automatically installed via the Chart, whatever the namespace name it is installed in.
#
- [] Improvement
- [] New feature
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation
#
</p>
#
#
@sureshms @harshach
=> fix: Use namespace Service for Airflow db host

charts/openmetadata/templates/check-db-migrations-job-hook.yaml
The `db-migrations-job` chart didn't have a parameterized `spec.serviceAccountName` field and as a result, db migrations couldn't authenticate using a serviceAccount.
When I added it with the correct value to my own deployment, the migrations ran w/out error, so this seems to be a complete fix.
#
#
n/a
#
#
@sureshms @harshach
=> [fixed] db-migrations-job did not have spec.serviceAccountName

charts/deps/Chart.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/deployment.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
Currently, there's no inbuilt config parameter to set the smtp sender mail address. This could be worked around using the `extraEnvs`, but providing an option under the smtp config directly seemed helpful.
If the sender mail values is not provided, we get the following error during sign-up (when we expect a verification email to be sent):
#
#
#
=> Provide option to configure smtp sender mail address

charts/deps/Chart.yaml, charts/deps/files/pod_template.kubernetes-helm-yaml, charts/deps/templates/configmap-pod-template.yaml, charts/deps/values.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/values.yaml
We are replicating the configMap structure for the pod_template_file and passing it as a constant name to the webserver.
This will create the `pod_template.yaml` file in the webserver regardless of the deployment name of the charts, which was the initial issue.
#
#
</p>
#
#
=> Add template with airflow dep structure

charts/openmetadata/templates/tests/test-connection.yaml
In our Kubernetes setup we use Polaris to enforce several best practices. This blocks the execution of the helm chart test because the required security context configuration is not present. This PR adds the security context configuration which is already defined in `values.yaml` to the helm chart test.
#
#
#
@akash-jain-10
=> Apply security context to chart test

charts/openmetadata/values.schema.json
Because the openmetadata chart is using the special `global` values and is not allowing any additional properties in the json schema this chart can effectively not be used as a dependency of a chart that also uses these special `global` values. The correct way to resolve this is to not use `global` and I see that an effort is being made in #143. Allowing additional values is an intermediate, non-breaking step to allow this chart to be used as a dependency (at the cost of not checking for additional properties within the first level of `global`).
#
#
#
@akash-jain-10
=> Allow additional properties in global

charts/openmetadata/templates/deployment.yaml
Enable saml keystore configs only on wantAssertionEncrypted or wantNameIdEncrypted
#
#
</p>
#
#
=> fix: enable saml keystore configs only on wantAssertionEncrypted or wantNameIdEncrypted

charts/deps/Chart.lock, charts/deps/Chart.yaml, charts/deps/templates/configmap-pod-template.yaml, charts/deps/values.yaml
Update MySQL Helm Chart Dependencies to `9.7.1`.
The Docker image associated with Chart Version `9.7.1` supports `arm64` architecture.
Add `sort_buffer_size` flag with `10M` as value.
This PR changes are tested with -
- Upgrades from previous versions
- Fresh Installs
#
#
#
=> feat: Bump MySQL App Version to 8.0.32

charts/openmetadata/README.md, charts/openmetadata/templates/servicemonitor.yaml, charts/openmetadata/values.yaml
Added support for creating ServiceMetrics resources using the Open Metadata helm chart so users can collect prometheus metrics using the [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator).
#
#
#
@harshach 
@akash-jain-10 
@Anuj359 
@dhruvinmaniar123
=> [FEAT] Add support for ServiceMonitor to grab prometheus metrics

charts/openmetadata/README.md, charts/openmetadata/values.yaml
This change updates the default values for the API url endpoints for airflow and openmetadata. This removes the need to specify them if a user is deploying things outside of the default cluster namespace making the quickstart just a bit more user friendly to setup. It does _not_ change existing clusters that are using the defaults as kubernetes will default to searching for the `pod.NAMESPACE.svc.cluster.local` if it does not find a DNS address for the `pod` url.
#
#
#
@sureshms @harshach
=> Shorten urls for openmetadata and dep services

charts/openmetadata/templates/deployment.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
Added support for `envFrom` statement in the app deployment.
With this feature, users will be able to define multiple environment variables in a single secret.
#
@akash-jain-10
=> [FEAT] Allow envFrom in OM deployment

charts/openmetadata/templates/deployment.yaml
The `run-db-migrations` init container is missing the security context that is defined in the `config`.
#
#
#
@akash-jain-10
=> Add missing security context to run-db-migrations init container

charts/deps/Chart.yaml, charts/deps/values.yaml, charts/openmetadata/Chart.yaml
ElasticSearch OOMKilled Issue. This seems to happen as we set the limits as well as `esJavaOpts` to be 1024M. It probably leaves no memory space for Container Processes and Kubernetes issues OOMKilled operation on elasticsearch pod.
#
#
#
=> Fix: ElasticSearch OOMKilled Issue

charts/openmetadata/templates/servicemonitor.yaml
The current version gives the following error when enabling the service monitor:
```
Error: YAML parse error on openmetadata/charts/openmetadata/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
```
That happens because the following yaml is being generated:
```
spec:
selector:
matchLabels:      app.kubernetes.io/name: openmetadata
app.kubernetes.io/instance: openmetadata
```
This should be fixed by using `nindent` instead of `indent`.
#
#
#
@akash-jain-10
=> Fix service monitor yaml

charts/deps/Chart.yaml
Upgrading the airflow base image from 2.5.3 to 2.6.3
=> Upgrade: airflow base image from 2.5.3 to 2.6.3

charts/deps/Chart.lock, charts/deps/Chart.yaml, charts/deps/values.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/_helpers.tpl, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
Breaking Changes -
- Removal of helm values `openmetadata.config.database.dbUseSSL`. This is deprecated and removed in favour of `openmetadata.config.database.dbParams`
- Update ElasticSearch Helm Chart Dependencies to `8.5.1`
Additions -
- `openmetadata.config.database.dbParams` to add addition Database Parameters as string format
- `openmetadata.config.migrationConfigs.extensionPath` for migration extensionPath
Fixes -
- Add Environment Variable for `openmetadata.config.pipelineServiceClientConfig.enabled` usage
- Fix schema constraints on OpenMetadata Repository Tags and Image names
#
=> feat: Prepare 1.2.0 Release

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/deps/Chart.yaml, charts/deps/values.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/_helpers.tpl, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
- fix: remove MIGRATION_EXTENSION_PATH
- fix: remove basic login extended configurations
#
#
#
=> feat: Prepare 1.2.1 Application Release

charts/openmetadata/templates/_helpers.tpl
I worked on unifying the way secret values are pulled to OM deployment. Currently this chart works under assumption that every secret value (cert, password, etc.) is pulled from k8s secrets but that doesn't have to be the case. In some deployments (such as ours) values are populated using external secrets provider (like hashicorp vault) using init containers. Since we don't want to reference k8s secrets this refactor provides unified approach towards disabling referencing secrets - if secretRef is empty then env variable won't be included in the deployment.
I also made couple of variables to leverage tpl (like cluster name) as users might want to inject namespace or release details into them.
#
#
<p align="center">For frontend related change, please link screenshots of your changes …
=> feat: unified approach for secrets referencing (and disabling)

charts/openmetadata/README.md, charts/openmetadata/templates/servicemonitor.yaml, charts/openmetadata/values.yaml
There is no way to specify labels that only go to the service monitor.  This PR adds the ability to add labels just to the service monitor.
#
#
</p>
#
#
@akash-jain-10
=> Add service monitor labels

charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/_helpers.tpl, charts/openmetadata/templates/secrets.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
The pipelineServiceClientConfig were missing a couple of parameters i.e. `truststorePath` and `truststorePassword` as per the new server release v1.2.4 ([reference](https://github.com/open-metadata/OpenMetadata/blob/1.2.4/conf/openmetadata.yaml#L272-L273)).
Hence updated the required files to include these parameters in helm charts.
#
#
</p>
#
#
=> feat: Prepare for 1.2.4 Release

charts/openmetadata/templates/_helpers.tpl, charts/openmetadata/templates/secrets.yaml
We have been reported with [an issue](https://openmetadata.slack.com/archives/C02B6955S4S/p1702923271280889) with the new helm chart (OMD app version - 1.2.3 and Chart version - 1.2.5)
Apparently, when the "hostIp" value is kept empty (or "") in the values.yaml file, the secrets template creates a null value secret for it which results in error while upgrading/installing the newer version of the helm chart.
With these changes, secret for hostIP won't be created unless it is non-empty.
#
#
#
@akash-jain-10
=> Fix null value secrets

charts/openmetadata/Chart.yaml, charts/openmetadata/templates/secrets.yaml
Fixes issue when deploying OM with ldap as authentication method.
#
#
#
=> fix: ldap configuration is not properly passed to authentication secret

charts/deps/Chart.yaml, charts/deps/values.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/_helpers.tpl, charts/openmetadata/templates/secrets.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
Preparing the Release 1.4.8 by doing the following:
- Update versions to `1.4.8`
- Add `spPrivateKey` to `values.yaml` as a secret
- Add `spPrivateKey` logic to `_helpers.tpl`
- Add `validateXml` to `values.yaml` as Boolean
- Add `validateXml` to `secrets.yaml` template
- Remove `wantNameIdEncrypted` from `secrets.yaml`
- Remove logic involving `wantNameIdEncrypted` from `_helpers.tpl`
- Update `values.schema.json` accordingly
These decisions were taken based on the following git diff
=> feat: Prepare Release 1.4.8

charts/openmetadata/values.yaml
This PR will replace the default binding host to be `0.0.0.0` instead of the hostname, which can lead to problems in kubernetes.
Fixes https://github.com/open-metadata/openmetadata-helm-charts/issues/256
#
#
@akash-jain-10
=> OpenMetadata - Change default bind address to 0.0.0.0

charts/openmetadata/templates/tests/test-connection.yaml
In a cluster where all nodes use taint, test pod will fail to schedule and keep in Pending state. This PR will make sure that test pod will be scheduled on the same node as openmetadata server pod.
#
#
#
=> openmetadata: add nodeSelector, affinity and tolerations on test connection pod

charts/openmetadata/values.schema.json
Add gcp (introduced [here](https://github.com/open-metadata/OpenMetadata/commit/9a31a352965333fdedb61886e3672a7240a11e59)) support in the secretsManager provider schema.
@akash-jain-10 @pellejador
=> CHORE - Add GCP to secretsManager.properties.provider enum

charts/deps/Chart.yaml, charts/deps/values.yaml, charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/secrets.yaml
- Update values to `1.5.9` release
- Fix #267 `AUTHENTICATION_LDAP_ALLOWED_HOSTNAMES`  incorrect value reference.
=> feat: Prepare 1.5.9 Release

charts/openmetadata/README.md, charts/openmetadata/templates/_helpers.tpl, charts/openmetadata/templates/cron_deploy_pipeline.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
Fixes #287 
#
- [  ] Bug fix
#
#
=> Feat: cron deploy pipelines

charts/openmetadata/templates/cron-deploy-pipelines.yaml, charts/openmetadata/templates/cron-reindex.yaml
Removed the redundant selector which is also not indented correctly in the CronJobs.
Fixes #300
#
#
#
=> openmetadata - Remove selectors from CronJobs

charts/deps/templates/_helpers.tpl, charts/deps/templates/cron-airflow-logs-cleanup.yaml, charts/deps/values.yaml
Adding a new cronjob to the dependencies chart, that takes care of removing Airflow logs when persistence is enabled.
=> Feat: cronjob to delete airflow logs

charts/openmetadata/templates/cron-deploy-pipelines.yaml, charts/openmetadata/templates/cron-reindex.yaml, charts/openmetadata/templates/deployment.yaml
* Fixes incorrect indentation on `metadata.annotations` in `cron-deployment-pipeline.yaml`, `cron-reindex.yaml` & `deployment.yaml`.
#
#
#
=> Fix indentation issue on annotations

charts/openmetadata/templates/hpa.yml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
This PR adds support for [Horizontal Pod Autoscaling (HPA)](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) for the OpenMetadata deployment. The default HPA metrics target CPU and memory utilization to scale the pods accordingly. By default, HPA is disabled in the values.yaml file.
#
#
#
=> Feat: Add horizontal pod autoscaling support

charts/openmetadata/README.md, charts/openmetadata/templates/cron-deploy-pipelines.yaml, charts/openmetadata/templates/cron-reindex.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
Added conditional inclusion of startingDeadlineSeconds to cronjob in OpenMetadata Helm charts to support OpenShift policies.
#
#
#
=> openmetadata: Add startingDeadlineSeconds to cronjob in OpenMetadata Helm charts to support OpenShift policies

charts/openmetadata/Chart.yaml, charts/openmetadata/README.md, charts/openmetadata/templates/tests/test-connection.yaml, charts/openmetadata/values.schema.json, charts/openmetadata/values.yaml
This change allows the use of HPA for OpenMetadata. 
Currently, this is not possible because the HPA cannot calculate the metrics because no resource requests (and limits?) are set for the pod `openmetadata-test-connection`:
```
Name:                                                     openmetadata-hpa
Namespace:                                                data
Labels:                                                   app=openmetadata
app.kubernetes.io/instance=openmetadata
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=openmetadata
app.kubernetes.io/version=1.9.1
helm.sh/chart=openmetadata-1.9.1
kustomize.toolkit.fluxcd.io/name=data-cdk8s
kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:                                              europace.de/logging_index: …
```
=> openmetadata: expose resource requests and limits for test-connection pod

charts/openmetadata/templates/deployment.yaml
Previously, `hpa` would not work because with a replica set explicity, the deployment would kill any spawned pod beyond the limit set by replica. With a value of 1 this would break hpa entirely. Moving forward, the deployment will not contain a value set for replicas but instead have hpa take care of scaling if hpa is enable.d
#
#
#
=> fix: exclude replicas from deployment if hpa
